spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: PRISM-PROJECT
          uri: http://localhost:8082/
          predicates:
            - Path=/users/**

server:
port: 8080
